---
language: python
python:
#  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
  - 3.6

services:
  - docker
    
cache:
  bundler:
  directories:
    - $HOME/.cache/pip
env:
#  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.1.0
#  - ANSIBLE_VERSION=2.3.1.0
#  - ANSIBLE_VERSION=2.2.2.0

#sudo: false
sudo: required
dist: trusty

virtualenv:
  system_site_packages: false
  
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
  - sudo pip install --upgrade pip
  - mkdir -p $HOME/.cache/pip/wheels
  # build wheel only if none present
  - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels scipy
  - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels cython
  # now install from it
  - pip install --no-index --find-links=$HOME/.cache/pip/wheels scipy
  - pip install --no-index --find-links=$HOME/.cache/pip/wheels cython
  - pip install coveralls
install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  - pip install molecule

  # Install dependencies.
  #- ansible-galaxy install alban.andrieu.subversion
  #- ansible-galaxy install alban.andrieu.xvbf
  - git clone https://github.com/AlbanAndrieu/Stouts.python.git python
  #- git clone https://github.com/debops/ansible-role-ansible.git ansible
  - git clone https://github.com/AlbanAndrieu/ansible-role-ntp.git geerlingguy.ntp
  - git clone https://github.com/AlbanAndrieu/ansible-locale.git locale
  - git clone https://github.com/AlbanAndrieu/ansible-hostname.git alban.andrieu.hostname
  - git clone https://github.com/AlbanAndrieu/ansible-java.git java
  - git clone https://github.com/AlbanAndrieu/ansible-common.git alban.andrieu.common
  #- git clone https://github.com/geerlingguy/ansible-role-firewall.git geerlingguy.firewall

script:
  # Check ansible version
  - ansible --version
  
  # Check syntax
  - ansible-playbook -i hosts --syntax-check administration.yml -e "python_versions=[2.7]"

  # Molecule test
  # - molecule test
  
  # First run
  - ansible-playbook -i hosts --connection=local --sudo -vvvv administration.yml -e "python_versions=[2.7]"

  #- coverage run --source=yourpackagename setup.py test

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - alban.andrieu@free.fr
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
