---
language: python
python: "2.7"
sudo: required
dist: trusty
env:
  - ANSIBLE_VERSION=1.9.2
cache: bundler
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install dependencies.
  #- ansible-galaxy install alban.andrieu.subversion
  #- ansible-galaxy install alban.andrieu.xvbf
  - git clone https://github.com/Stouts/Stouts.python.git python
  - git clone https://github.com/debops/ansible-role-ansible.git ansible
  - git clone https://github.com/geerlingguy/ansible-role-ntp.git geerlingguy.ntp
  - git clone https://github.com/AlbanAndrieu/ansible-locale.git locale
  - git clone https://github.com/AlbanAndrieu/ansible-hostname.git alban.andrieu.hostname
  - git clone https://github.com/AlbanAndrieu/ansible-java.git java
  - git clone https://github.com/AlbanAndrieu/ansible-common.git alban.andrieu.common
  #- git clone https://github.com/geerlingguy/ansible-role-firewall.git geerlingguy.firewall

script:
  - sudo ansible --version
  - export ANSIBLE_ROLES_PATH="../"
  - ls -lrta
#  - echo localhost > inventory
  - ansible-playbook -i hosts --syntax-check administration.yml
  - ansible-playbook -i hosts --connection=local --sudo -vvvv administration.yml
