---
- hosts: all
  sudo: true  

  vars_files:
  - [ "vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml", "vars/{{ ansible_distribution }}.yml" ]
    
  roles:
    - { role: ./,
        ntp_timezone: Europe/Paris
      }
