---
- hosts: all
  sudo: true  

  roles:
    - { role: ./,
        ntp_timezone: Europe/Paris,
        root_ssh_rsa_key_file: "",
        root_ssh_dsa_key_file: "",
        root_ssh_authorized_keys_enabled: no
      }
