---
# sudo ansible-playbook -i hosts -c local -v administration.yml -vvvv | tee setup.log

- name: Assert platform is supported
  hosts: all
  remote_user: root
  gather_facts: true

  tasks:
    - name: Assert platform is supported
      assert:
        that:
          - ansible_os_family in ['Debian', 'RedHat', 'CentOS', 'Windows', 'Solaris']
          - ansible_architecture in ['x86_64']

#- hosts: localhost
#
#  tasks:
#    - name: Install Ansible-Galaxy dependencies
#      shell: ansible-galaxy install -r requirements.yml -p ./roles/
#      ignore_errors: true
      
#- import_playbook: python.yml
      
- hosts: all
  become: true

  roles:
    - role: ansible-administration

  vars:
    ntp_timezone: Europe/Paris
    root_ssh_rsa_key_file: ""
    root_ssh_dsa_key_file: ""
    root_ssh_authorized_keys_enabled: false
