
- import_tasks: nis.yml
  when: nis_enabled

- import_tasks: autofs.yml
  when: autofs_enabled

- name: administration | Start services
  service: name={{ item }} state=started enabled=yes
  with_items:
  - rpcbind
  - nfslock
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')
  tags: service
  become: yes

- name: administration | Start the autofs service
  service: name=autofs state=started enabled=true
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')
  tags: service
  become: yes

- meta: flush_handlers

- pause: 
    seconds: 30
