---
# This should work too / #2372
# - name: Pushes user key to root's on vagrant boxes
#   action: authorized_key key=$FILE($item) user=root
#   first_available_file:
#     - ~/.ssh/id_dsa.pub
#     - ~/.ssh/id_rsa.pub

- name: Creates destination directory
  # Workaround for #2372
  file: state=directory mode=0700 dest=/root/.ssh/

- name: Pushes user's rsa key to root's box (it's ok if this TASK fails)
  copy: >
    src={{root_ssh_rsa_key_file}}
    dest={{root_home}}/.ssh/authorized_keys
    owner={{root_user}}
#    group={{root_group}}
    mode=0600
  sudo: yes    
#  when: root_ssh_rsa_key_file != ""  
  register: rsa
  ignore_errors: yes

- name: Pushes user's dsa key to root's box (it's ok if this TASK fails)
  copy: >
    src={{root_ssh_dsa_key_file}}
    dest={{root_home}}/.ssh/authorized_keys
    owner={{root_user}}
#    group={{root_group}}
    mode=0600
  sudo: yes    
  when: root_ssh_dsa_key_file != ""  
  when: rsa|failed  
