---

- name: administration | Install python-selinux
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ util_pkg_state|default('present') }} update_cache=yes"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: package
  with_items:
   - python-selinux
   - selinux-policy-default
  become: true
  
- name: administration | Disabled SELinux
  selinux: state=disabled
  when: not selinux_enabled and not ansible_check_mode
  become: true
  ignore_errors: true

- meta: flush_handlers
  when: not selinux_enabled
