---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart ntp
  systemd:
    state: restarted
    daemon_reload: true
    name: ntpd
  become: true

- name: restart nis
  systemd:
    state: restarted
    daemon_reload: true
    name: nis
  become: true

- name: restart NetworkManager
  systemd:
    state: restarted
    daemon_reload: true
    name: NetworkManager
  become: true

- name: restart yp
  systemd:
    state: restarted
    daemon_reload: true
    name: ypbind
  become: true

- name: restart autofs
  systemd:
    state: restarted
    daemon_reload: true
    name: autofs
  become: true

# - name: restart iptables
#   service: name=iptables state=restarted
