---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart ntp
  service: name=ntpd state=restarted
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')
  become: yes
  
- name: restart ntp
  service: name=ntp state=restarted
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  become: yes

- name: restart nis
  service: name=nis state=restarted
  become: yes

- name: restart yp
  service: name=ypbind state=restarted
  become: yes
      
- name: restart autofs
  service: name=autofs state=restarted
  become: yes      
      
#- name: restart iptables
#  service: name=iptables state=restarted
