---

- name: Converge
  hosts: centos_7_administration

  roles:
    - role: geerlingguy.repo-epel

- name: Converge
  hosts: all

  roles:
    - role: alban.andrieu.administration
      verbose: true
  no_log: false
